export const REAL_EXE_MANUAL_VALIDATION_GUIDE_REPO_PATH = 'docs\\REAL_EXE_MANUAL_VALIDATION_GUIDE.md';
export const REAL_EXE_MANUAL_VALIDATION_GUIDE_PACKAGE_PATH = 'REAL_EXE_MANUAL_VALIDATION_GUIDE.md';

export function formatRealExeManualValidationGuideQuickCopy() {
  return [
    '联机助手 v0.1 真实 EXE 人工验证简表',
    '',
    '完整指南：',
    `- 仓库内：${REAL_EXE_MANUAL_VALIDATION_GUIDE_REPO_PATH}`,
    `- 发布包内：${REAL_EXE_MANUAL_VALIDATION_GUIDE_PACKAGE_PATH}`,
    '',
    '验证前命令：',
    'npm run build',
    'cargo check --manifest-path src-tauri\\Cargo.toml',
    'npm run adapter:validate',
    'npm run release:preflight',
    '',
    'A. 真实 EXE 与基础体验',
    '- 从 src-tauri\\target\\release\\lan-helper.exe 启动，不只看 npm dev。',
    '- 确认没有白色命令框、透明残留窗口或异常多开的主程序。',
    '- 二次进入游戏扫描、组网中心、Terraria 向导、推荐方案、诊断页时，应保留上次内容且不卡顿。',
    '',
    'B. 邀请包一键加入',
    '- 房主生成邀请包前必须已启动组网、检测端口、分配好友虚拟 IP。',
    '- 好友粘贴邀请包后先测试“仅填入参数”，再测试“保存并启动 n2n”。',
    '- 观察加入结果卡片：成功 / 等待 ACK / 失败。',
    '- 成功后应提示在游戏内连接房主虚拟 IP 和端口。',
    '- 失败时应进入诊断，并能复制错误信息给房主。',
    '',
    'C. 房主开房向导',
    '- 按“选择游戏 → 推荐方案 → 启动组网 → 启动服务端/游戏 → 分配好友 IP → 生成邀请包”走一遍。',
    '- Terraria 需要确认 7777 或实际端口监听，服务端 30 秒内不退出。',
    '- 未分配好友 IP 时，不应允许复制不完整 LAN 邀请。',
    '',
    'D. adapter 与非 LAN 边界',
    '- 执行 npm run adapter:validate，确认 Warnings=0、Errors=0 或能解释。',
    '- Cuphead / 本地同屏类游戏不能生成 LAN 邀请，不能推荐 n2n，应推荐 Steam Remote Play 或 Sunshine + Moonlight。',
    '',
    'E. 诊断修复中心',
    '- 对 n2n 未启动、Supernode 无响应、端口不通、edge.exe 缺失、版本不匹配等场景生成诊断。',
    '- 每个问题应有原因说明、一键修复或手动命令、自动复测、复制报告。',
    '',
    '记录方式：',
    '- 在诊断页“真实 EXE 人工验证”区域逐项标记 PASS / FAIL / PENDING。',
    '- 复制验证清单并写入 docs\\RELEASE_VALIDATION_LOG.md。',
    '- 双机或真实游戏内加入未测时必须保持 PENDING，不要写成 PASS。',
  ].join('\n');
}
